### ISSUE TITLE
Feature Addition :  Chunkify

### ISSUE THREAD

**Issue by LORDLYAMIGO** [opencodeiiita/Limen#1]
# Feature Addition : Chunkify

## Description
Implement a utility to split an input file into smaller chunks, with specific formatting requirements for naming and content organization.

## Requirements
1. **Input**: Accept a file as input.  
2. **File Splitting**: Break the file into smaller chunks.  
3. **Chunk Naming**:  
    - The first chunk (which contains the header of the input file) should be named `0.tysm`.  
    - The remaining chunks should be named sequentially, starting from `1.tysm`, `2.tysm`, ..., up to `n.tysm`.  
4. **Header Data**:  
    - Add the following header data at the beginning of `0.tysm`:  
      ```xml
      <tysm>"$input_file_extension","$number_of_chunks"</tysm>
      ```
    - `$input_file_extension` is the extension of the input file.  
    - `$number_of_chunks` is the total number of chunks the input file is split into.  
5. **Output Directory**:  
    - Store all the chunks in a new local folder named in the following format:  
      ```
      input_filename -> TYSM
      ```

## Acceptance Criteria
- The utility should handle large files efficiently.  
- Generated chunks must adhere to the specified naming and content structure.  
- The output directory must always match the input file's name with the appended `-> TYSM`.  

## Additional Notes
- Ensure the implementation is robust, handling edge cases like empty files or files without an extension.  
- Provide error handling and informative logs to guide users in case of invalid inputs.  

## Submission Last Date 22/12/24 Only Python or Rust is allowed
# View Submission.txt in submission folder for how to submit

**Comment by official-ashutosh** [comment]
claim
