### ISSUE TITLE
Rank and Print a Permutation  

### ISSUE THREAD

**Issue by LORDLYAMIGO** [opencodeiiita/Limen#17]
# Feature Addition: Rank and Print a Permutation  

## Description  
Implement a program to generate and print a specific ranked permutation from a set of numbers `{1, 2, ..., N}` based on user input.  

## Requirements  
1. **Input**:  
   - `N`: The length of the number series.  
   - `Rank`: The rank of the desired permutation (1-indexed).  
   - `Rank can be input in Base64 or in Decimal format` 
   - If Rank is greater than maximum rank for N then perform modulo remainder with respect to maximum rank.

2. **Permutation Calculation**:  
   - Generate the `Rank`-th permutation of the set `{1, 2, ..., N}` in lexicographical order.  

3. **Output**:  
   - Print the permutation corresponding to the given `Rank`.  

4. **Constraints**:  
   - Handle edge cases where `Rank` is invalid (e.g., larger than `N!`).  
   - Efficiently compute the desired permutation without generating all permutations.  

## Example  
- **Input**:  
  ```
  N = 5  
  Rank = 98
  ```  
- **Output**:  
  ```
  5,1,2,3,4
  ```  

## Acceptance Criteria  
- The program must compute the desired permutation efficiently for large values of `1< N < 10^6`
- Output must be correct and in the required format.  
- The program should gracefully handle invalid ranks.  

## Submission  
- **FCFS**
- **Languages Allowed**: C++ or Python or Rust
- Refer to `submission.txt` in the submission folder for submission guidelines.

**Comment by kanav67** [comment]
claim

**Comment by LORDLYAMIGO** [comment]
\info

**Comment by PriyamJChakrabarty** [comment]
claim

**Comment by kanav67** [comment]
@LORDLYAMIGO please close the issue
